apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-admin-config
  namespace: rabbitmq-admin
data:
  # Configuration values will be injected during deployment
  # These are placeholders - actual values will come from .env files
  RABBITMQ_ADMIN_IMAGE_TAG: "latest"
  AUDIT_WRITE_OPERATIONS_ENABLED: ""
  AUDIT_RETENTION_ENABLED: ""
  AUDIT_RETENTION_DAYS: ""
  AUDIT_RETENTION_CLEAN_SCHEDULE: ""
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "production,docker"
