spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rabbitmq_admin
    username: ${DB_USERNAME:rabbitmq_admin}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

# Docker application configuration
app:
  audit:
    write-operations:
      enabled: ${AUDIT_WRITE_OPERATIONS_ENABLED:false}
      retention-days: ${AUDIT_RETENTION_DAYS:90}
      batch-size: ${AUDIT_BATCH_SIZE:100}
      async-processing: ${AUDIT_ASYNC_PROCESSING:true}

logging:
  level:
    "[com.rabbitmq.admin]": INFO
    "[com.rabbitmq.admin.security]": INFO
    "[org.springframework.security]": INFO
    "[org.flywaydb]": INFO
